### ISSUE TITLE
This library's future

### ISSUE THREAD

**Issue by pm64** [mmccall10/el-transition#6]
This library stands to serve an important role for applications seeking to support transition effects without taking a cumbersome dependency on something like Alpine.js. But a visitor to this repository must wonder if the library has a future? It looks like PRs are piling up and it's not clear if there is any intention of maintaining this library. Can you please help set the appropriate expectation by advising as to whether this project will receive attention going forward?

**Comment by mmccall10** [comment]
Hey, thanks for the concern. This is a very small simple library. I would not expect much activity outside of any issues around browser compatibility. So far there hasn't been any.

**Comment by pm64** [comment]
Thank you @mmccall10 for the clarification, and big thanks on behalf of the community for contributing this important library.
