### ISSUE TITLE
Is project alive?

### ISSUE THREAD

**Issue by pm64** [mmccall10/el-transition#8]
This library is an excellent lightweight alternative to Alpine.js and similar, but we worry about adopting something that's not actively maintained. I see there have been 2 open pull requests for some time. Is this the end of the line for el-transition?

**Comment by mmccall10** [comment]
Hi @pm64  thanks for you concern. It's still alive. It's very lightweight and quite simple. If there is any concern feel free to fork it or copy the index.js contents into your project.
